### ISSUE TITLE
Variable precedence

### ISSUE THREAD

**Issue by nikhilo** [kolypto/j2cli#12]
I want to define a few variables in say `json` and then override some of them using some other data input method, say environment variable. I don't think it's possible to do this (overriding) right now. It accepts only one data input method at a time.

**Comment by x2es** [comment]
+1

**Comment by 3fr61n** [comment]
#31  I think this could be a workaround for this issue as well

**Comment by kolypto** [comment]
Now, in the new release, you can override top-level variables with environment variables: use `--import-env=`. 

Another solution would be to use some JSON-merging script before using j2cli. I really don't think that overriding is something this tool should do. This is UNIX philosophy: "Make each program do one thing well.". Just one thing :)
