### ISSUE TITLE
character is changed, when converting

### ISSUE THREAD

**Issue by ozbillwang** [kolypto/j2cli#25]
When converting, why it changed the value `false` to `False`? (capital letter)

```
# cat a.j2
{
  "key": {
    "enabled": {{ app.enabled }}
}

# cat a.json
{
  "app": {
    "enabled": false
  }
}

# j2 a.j2 a.json
{
  "key": {
    "enabled": False
}
```

**Comment by kolypto** [comment]
This is Python behavior: it's boolean literal has a capital `F`.

Use Jinja2 `|lower` filter: `{{ bool_variable|str|lower }}`
