### ISSUE TITLE
yaml.load() without Loader is deprecated

### ISSUE THREAD

**Issue by murmelade** [kolypto/j2cli#33]
Hi, 

after upgrade to pyyaml-5.1 some python deprecation warnings are shown.

**Message**
> /usr/local/lib/python3.6/site-packages/j2cli/context.py:88: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> return yaml.load(data_string)

**Environment**
OS: Centos7 
Python3: v3.6.6 (via EPEL)
j2cli: v0.3.5.post1 (via pip3)
Jinja2: v2.10 (via pip3)
PyYAML: v5.1 (via pip3)

Thanks!

**Comment by kolypto** [comment]
Fixed in 0.3.6. Thanks! :)

**Comment by jswarren** [comment]
`FullLoader` was not [added to PyYAML until version 5.1](https://github.com/yaml/pyyaml/blob/e471e86bf6dabdad45a1438c20a4a5c033eb9034/CHANGES#L33), which means `j2cli` is now broken for anyone using an older version of PyYAML. A version constraint should probably be added in `setup.py`.

**Comment by kolypto** [comment]
Sorry! I removed the broken release from pypi for now

**Comment by kolypto** [comment]
Fixed in `0.3.6.post1`
