### ISSUE TITLE
Is there an easy way to merge environment variables from different sources?

### ISSUE THREAD

**Issue by paulcdejean** [kolypto/j2cli#35]
I'd like to use a combination of environment variables and data from a yml file when compiling a j2 file. Is there any easy way to do this?

**Comment by kolypto** [comment]
Hm. You'll have to merge the two into something that's singular: it may be importing environment variables into your yml file, or it may be exporting yml data into the environment somehow.

Perhaps, the easiest (but somewhat akwward) way would be to have some Jinja2 placeholders inside your yml file:

```yaml
# setttings.yml.template
user:
    login: admin
    password: {{ USER_PASS }}
```

Then, treating it as a template, compile it into a second yml file:

```bash
$ USER_PASS="qwerty123" j2 settings.yml.template > settings.yml
```

Now, having a `settings.yml` file with environment variables in it, you use it as the context for rendering another template:


```bash
$ j2 your-file.j2 settings.yaml
```

**Comment by kolypto** [comment]
Also, consider making a custom Jinja2 filter:

```python
# filters.py
def env_override(default_value, key):
  return os.getenv(key, default_value)
```

Now, you can import this filter with `--filters` command-line option:

```bash
$ j2cli --filters filters.py ...
```

And use it like this in your templates:

```jinja2
{{ "default" | env_override("USER_PASS") }}
```

**Comment by kolypto** [comment]
Alright, here's the best of all: I just released a new version of `j2cli` for you, which supports the `|env` filter in the template.

Have a look: [`|env` filter](/kolypto/j2cli#envvarname-defaultnone)
