### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by mike-carey** [kolypto/j2cli#82]
Hello @kolypto, I am wondering if this project is still maintained.  I would like to add functionality and some updates, but I noticed this repo has not gotten attention for quite some time.

**Comment by kolypto** [comment]
Hi! 
This project gets some interest, but I'm not maintaining it =\

Maintainer wanteed!
Discussion: https://github.com/kolypto/j2cli/discussions/83

**Comment by mike-carey** [comment]
Understood, thank you very much!!  I will take a look at some of the forks mentioned in the discussion.
